version: "2"
services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  web:
      container_name: web
      restart: always
      build: ./web
      ports:
        - "8080:80"
      links:
        - api